version: "3"
services:

  corona:
    image: coronacharts
    build: .
    restart: always
    dns:
      - 8.8.8.8
      - 9.9.9.9
    ports:
      - "8080:8080"
    networks:
      - cmsnetwork

  api:
    image: cms-api:1.0
    build: api
    restart: always
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "4006:4006"
    networks:
      - cmsnetwork

  mongo:
    image: mongojson
    build: mongoserver
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/data:/data/db
      - ./mongodb/backup:/data/backup
    networks:
      - cmsnetwork

networks:
  cmsnetwork:


  # fetch:
  #   image: cms-fetch:1.0
  #   build: fetchdm
  #   volumes:
  #     - ./fetchdm/logs:/app/logs
  #   networks:
  #     - cmsnetwork
